### ISSUE TITLE
Error with yeoman

### ISSUE THREAD

**Issue by KamiKillertO** [nicksrandall/inquierer-directory#11]
Hello,

I've tried using it in a yeoman generator project. But I've got this error :

```
TypeError: Cannot read property 'then' of undefined
    at C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\node_modules\inquirer\lib\ui\prompt.js:79:50
    at tryCatcher (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:63:31)
    at Defer.subscribeCore (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:2536:37)
    at Defer.tryCatcher (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:63:31)
    at setDisposable (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:2082:46)
    at Defer.Rx.ObservableBase.ObservableBase._subscribe (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:2097:9)
    at Defer.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:2034:19)
    at MergeObserver.handleSubscribe (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:3525:28)
    at MergeObserver.next (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:3531:14)
    at MergeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\KillertO\AppData\Roaming\npm\node_modules\yo\node_modules\rx\dist\rx.js:1762:31)
events.js:154
      throw er; // Unhandled 'error' event
```

Here's my code :

```
'use strict';
var yeoman = require('yeoman-generator'),
    chalk = require('chalk'),
    yosay = require('yosay'),
    slug = require('slug');

module.exports = yeoman.Base.extend({
    initializing: function() {
        this.env.adapter.promptModule.registerPrompt('directory', require('inquirer-directory'));
        this.props = {};
    },
    prompting: function() {
        // Have Yeoman greet the user.
        this.log(yosay(
            'Welcome to the cool ' + chalk.red('generator-yo-web') + ' generator!'
        ));

        var prompts = [{
            type: 'input',
            name: 'appname',
            message: 'Project name ',
            default: 'web-app'
        }, {
            type: 'directory',
            name: 'destinationFolder',
            message: 'Destination folder',
            basePath: process.cwd()
        }];

        return this.prompt(prompts).then(function(answer) {
            this.props.appname = slug(answer.appname);
            this.props.destinationRoot = answer.destinationFolder.concat('/' + this.props.appname);
        }.bind(this));
    },

    default: function() {},
    writing: function() {},
    install: function() {}
});

```

**Comment by nicksrandall** [comment]
Sorry I'm just now seeing this. What version of node are you using? What version of Inquirier?

**Comment by KamiKillertO** [comment]
I was using node 5.5 and Inquirer 1.1.2.
I solved the issue by updating Inquirer

**Comment by nicksrandall** [comment]
fixed via https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.1.0

**Comment by KamiKillertO** [comment]
Thanks
