### ISSUE TITLE
Error with latest inquirer.js

### ISSUE THREAD

**Issue by idanblich** [nicksrandall/inquierer-directory#8]
Hi , 
When using [inquirer 1.0.2](https://github.com/SBoudrias/Inquirer.js/releases/tag/v1.0.2) and[ inquirer-directory 2.0.0 ](https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.0.0)  the code is broken , 
this is the error i got : 

```
readline.js:925
            throw err;
            ^

TypeError: cb is not a function
    at module.exports (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/run-async/index.js:23:5)
    at Prompt.filter (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/inquirer/lib/prompts/base.js:128:3)
    at Prompt.<anonymous> (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/inquirer/lib/prompts/base.js:56:10)

    at Prompt.onSubmit (/Users/idan/readytodeploy/node_modules/inquirer-directory/index.js:234:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/inqu
irer/node_modules/rx-lite/rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_mo
dules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/inquirer/node_modules/rx-lite/rx.lite
.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/inquirer/node_modules/rx-lite/rx.
lite.js:5782:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_m
odules/inquirer/node_modules/rx-lite/rx.lite.js:1469:31)
    at AnonymousObserver._onNext (/Users/idan/readytodeploy/node_modules/inquirer-directory/node_modules/inquirer/node_modules/rx-lite/rx.lite.js
:4234:13)
```

**Comment by richardhomewood** [comment]
Upgrading the inquirer dependency to the latest version fixed this for me

**Comment by richardhomewood** [comment]
Created a small pull request for this if that helps!

**Comment by nicksrandall** [comment]
fixed via https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.1.0
